/**
 *
 * $Id$
 */
package uk.ac.bham.mongoMap.model.mongo.validation;

import org.eclipse.emf.common.util.EList;

import uk.ac.bham.mongoMap.model.mongo.Document;
import uk.ac.bham.mongoMap.model.mongo.UniqueIndex;

/**
 * A sample validator interface for {@link uk.ac.bham.mongoMap.model.mongo.Collection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CollectionValidator {
	boolean validate();

	boolean validateDocuments(EList<Document> value);
	boolean validateUniqueIndices(EList<UniqueIndex> value);
	boolean validateName(String value);
}
