/**
 *
 * $Id$
 */
package uk.ac.bham.mongoMap.model.mongo.validation;

import org.eclipse.emf.common.util.EList;

import uk.ac.bham.mongoMap.model.mongo.Id;
import uk.ac.bham.mongoMap.model.mongo.Key;

/**
 * A sample validator interface for {@link uk.ac.bham.mongoMap.model.mongo.Document}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentValidator {
	boolean validate();

	boolean validateKeys(EList<Key> value);
	boolean validateId(Id value);
}
