/**
 *
 * $Id$
 */
package uk.ac.bham.mongoMap.model.mongo.validation;

import uk.ac.bham.mongoMap.model.sql.Datatye;

/**
 * A sample validator interface for {@link uk.ac.bham.mongoMap.model.mongo.Value}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValueValidator {
	boolean validate();

	boolean validateType(Datatye value);
	boolean validateValue(Object value);
}
