/**
 *
 * $Id$
 */
package metamodel.validation;

import metamodel.ColumnType;
import metamodel.Sequence;

/**
 * A sample validator interface for {@link metamodel.Column}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ColumnValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateType(ColumnType value);
	boolean validateNullable(boolean value);
	boolean validateSequenceColumn(Sequence value);
}
