/**
 *
 * $Id$
 */
package metamodel.validation;


/**
 * A sample validator interface for {@link metamodel.Sequence}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SequenceValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateMinValue(int value);
	boolean validateMaxValue(long value);
	boolean validateIncrement(int value);
	boolean validateStart(long value);
	boolean validateCurrentValue(long value);
}
