/**
 *
 * $Id$
 */
package uk.ac.bham.mongoMap.model.sql.validation;

import org.eclipse.emf.common.util.EList;

import uk.ac.bham.mongoMap.model.sql.Column;
import uk.ac.bham.mongoMap.model.sql.ConstraintType;

/**
 * A sample validator interface for {@link uk.ac.bham.mongoMap.model.sql.Constraint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateType(ConstraintType value);
	boolean validateReference(String value);
	boolean validateColumn(EList<Column> value);
}
