/**
 *
 * $Id$
 */
package uk.ac.bham.mongoMap.model.sql.validation;

import org.eclipse.emf.common.util.EList;

import uk.ac.bham.mongoMap.model.sql.Sequence;
import uk.ac.bham.mongoMap.model.sql.Table;

/**
 * A sample validator interface for {@link uk.ac.bham.mongoMap.model.sql.Database}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DatabaseValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateTable(EList<Table> value);
	boolean validateSequences(EList<Sequence> value);
}
