/**
 *
 * $Id$
 */
package uk.ac.bham.mongoMap.model.sql.validation;


/**
 * A sample validator interface for {@link uk.ac.bham.mongoMap.model.sql.Sequence}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SequenceValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateMinValue(int value);
	boolean validateMaxValue(long value);
	boolean validateIncrementby(int value);
	boolean validateStartwith(long value);
	boolean validateCurrentValue(long value);
	boolean validateCycle(boolean value);
}
